#!/bin/csh
#
cat /dev/null >linkfile

set others="ALA CYS CYM CYF CSP ASP GLU PHE HIS NEP ILE LYS ALY MLY MLZ M3L LEU MET ASN PRO GLN ARG SER SEP THR THP TOP VAL TRP TYR TYP TYS HYP"


cat <<_Eod_ >>linkfile
remarks 
remarks this is a macro to define standard protein peptide bonds
remarks and termini to generate a protein sequence.
 
 set message ? end eval (\$old_message=\$result) set echo ? end eval (\$old_echo=\$result)
 set message=off echo=off end


 checkversion 1.3

_Eod_


echo "link  ppgp head - GLY tail + PRO end" >>linkfile
echo "link  ppgp head - GLY tail + HYP end" >>linkfile
echo "link  ppgg head - GLY tail + GLY end" >>linkfile

# Special links to GLY
#
foreach i (GLY)
  echo '{ special link to GLY}' >>linkfile
  foreach j (ACE $others)
       echo "link ppg1 head - "$j" tail + "$i" end" >>linkfile
  end
  echo ' ' >>linkfile
end

# Special links from GLY
#
foreach i (GLY)
  echo '{ special link from GLY}' >>linkfile
  foreach j ($others CTN) 
       echo "link ppg2 head - "$i" tail + "$j" end" >>linkfile
  end
  echo ' ' >>linkfile
end

# Special links to PRO and HYP
#
foreach i (PRO HYP)
  echo '{ special link to PRO and HYP}' >>linkfile
  foreach j (ACE $others)
       echo "link pepp head - "$j" tail + "$i" end" >>linkfile
  end
  echo ' ' >>linkfile
end

# all others
#
foreach i (ACE $others)
  echo '{ peptide linkages for '$i' }' >>linkfile
  foreach j ($others CTN)
       echo "link pept head - "$i" tail + "$j" end" >>linkfile
  end
  echo ' ' >>linkfile
end

cat <<_Eod_ >>linkfile

first IONS tail + NA1 end
first IONS tail + CL1 end
first IONS tail + CA2 end
first IONS tail + CU1 end
first IONS tail + CU2 end
first IONS tail + CU3 end
first IONS tail + MG2 end
first IONS tail + FE2 end
first IONS tail + ZN2 end
first IONS tail + SO4 end
first IONS tail + PO4 end
first IONS tail + HEB end
first IONS tail + HEC end
first IONS tail + TIP3 end
first IONS tail + GTP end
first IONS tail + DRG end

first PROP tail + PRO end
first PROP tail + HYP end

first ACET tail + ACE end

_Eod_

foreach i ($others) 
  echo "first NTER tail + "$i" end" >>linkfile
end

cat <<_Eod_ >>linkfile

last  IONS head - NA1            end
last  IONS head - CL1            end
last  IONS head - CA2            end
last  IONS head - CU1            end
last  IONS head - CU2            end
last  IONS head - CU3            end
last  IONS head - MG2            end
last  IONS head - FE2            end
last  IONS head - ZN2            end
last  IONS head - SO4            end
last  IONS head - PO4            end
last  IONS head - HEB            end
last  IONS head - HEC            end
last  IONS head - TIP3           end
last  IONS head - GTP            end
last  IONS head - DRG            end

_Eod_


foreach i ($others) 
  echo "last CTER head - "$i" end" >>linkfile
end

cat <<_Eod_ >>linkfile

set message=\$old_message echo=\$old_echo end

_Eod_

