Description of PowerSat
Home > EPRtoolbox > cw > PowerSat > PowerSat.m
PowerSat
PURPOSE
POWERSAT Open, analyse and plot power saturation experiments
SYNOPSIS
function varargout = PowerSat(varargin)
DESCRIPTION
 POWERSAT Open, analyse and plot power saturation experiments
      POWERSAT, is designed as a complete solution for power saturation
      experiments. Taking raw spectra straight from the spectrometer and
      turning them into Power Saturation curves and accessibility
      parameters (Pi values) in seconds.
      POWERSAT, loads Bruker BES3T files either as a single file (actually
      3 files with the extensions .DTA / .DSC / .YGF extensions) or an
      entire folder of files (with the Bruker BES3T format (.DTA/.DSC) or
      the older Bruker format still used on EMX machines (.spc/.par). If a
      folder load method is used then each of the oxygen, nitrogen, NiEDDA
      and DPPH experiments data files need to be in a different folders.
      REFERENCES:
      ===========
      This calculations in this program are all derived from:
       Accessibility of Nitroxide Side Chains: Absolute Heisenberg
       Exchange Rates from Power Saturation EPR
       Biophysical Journal, vol 89 (2005) 2103 - 2112.
       DOI: 10.1529/biophysj.105.059063
      Equations for first and second derivative Gaussian and Lorentzian
       functions are taken from:
       http://www.hulinks.co.jp/software/peakfit/functions.html
      RELEASE NOTES:
      ==============
      Since POWERSAT v12.7 uses MATLAB's Curve Fitting toolbox for the
      fitting of the Gaussian or Lorentzian profiles to raw data as well
      as fitting power saturation curves. This is due to the CFtoolbox
      giving greater control and flexibility to fitting.
      POWERSAT v12.6 and before instead used the freely
      available toolbox EzyFit.
       www.fast.u-psud.fr/ezyfit/
      This method was discontinued as the EzyFit toolbox allows for no
      restriction of coefficient ranges during fitting. This often meant
      that during the fitting of the power saturation curves that a
      local minima for "a" was found below zero, giving an incorrect fit;
      usually in the shape of a diagonal line with a loop in the middle.
      This problem whilst promised to be fixed in an upcoming release of
      Ezyfit (in personal correspondance with the author) has been
      outstanding for over a year.
      If users, do not wish to use the CFtoolbox then it is recommended to
      install a version of POWERSAT prior to v12.7, still available at:
      http://sourceforge.net/projects/eprtoolbox/files/PowerSat/PowerSat_v11.11.zip/download
      Demonstration videos are available on YouTube:
       Basic functionality - http://youtu.be/n8wWRzHoF-8
       Fitting options     - http://youtu.be/DstC7ysrYG0
 Syntax:  PowerSat
 Inputs:
    input1 - n/a
 Outputs:
    output1 - n/a
 Example:
    see http://morganbye.net/PowerSat
        http://youtu.be/n8wWRzHoF-8
        http://youtu.be/DstC7ysrYG0
 Other m-files required:
    PowerSat.fig
    Curve Fitting Toolbox - fit, fittype, coeffvalues
    BrukerRead
 Subfunctions:         /_private (folder)
 MAT-files required:   none
CROSS-REFERENCE INFORMATION
This function calls:
PS_DetachPlot PS_DETACHPLOT Export a plot from within the GUI
PS_ExportToOrigin PS_EXPORTTOORIGIN Export the power saturation spectra to an Origin
PS_FileLoad PS_FileLoad Load power saturation experiments
PS_Help_About PS_Help
PS_Help_Help PS_Help
PS_Plot1 PS_PLOT1 Plot the raw power saturation spectra
PS_PlotPS PS_PLOTPS Plot the power saturation curves
PS_SavePlot PS_SAVEPLOT Export a plot from within the GUI
This function is called by:
SUBFUNCTIONS
function PowerSat_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = PowerSat_OutputFcn(hObject, eventdata, handles)
function panel_Plot_SelectionChangeFcn(hObject, eventdata, handles)
function edit_OxyHigh_Callback(hObject, eventdata, handles)
function edit_OxyHigh_CreateFcn(hObject, eventdata, handles)
function edit_OxyLow_Callback(hObject, eventdata, handles)
function edit_OxyLow_CreateFcn(hObject, eventdata, handles)
function edit_N2High_Callback(hObject, eventdata, handles)
function edit_N2High_CreateFcn(hObject, eventdata, handles)
function edit_N2Low_Callback(hObject, eventdata, handles)
function edit_N2Low_CreateFcn(hObject, eventdata, handles)
function edit_NiHigh_Callback(hObject, eventdata, handles)
function edit_NiHigh_CreateFcn(hObject, eventdata, handles)
function edit_NiLow_Callback(hObject, eventdata, handles)
function edit_NiLow_CreateFcn(hObject, eventdata, handles)
function edit_DPPHHigh_Callback(hObject, eventdata, handles)
function edit_DPPHHigh_CreateFcn(hObject, eventdata, handles)
function edit_DPPHLow_Callback(hObject, eventdata, handles)
function edit_DPPHLow_CreateFcn(hObject, eventdata, handles)
function checkbox_autozero_Callback(hObject, eventdata, handles)
function dropdown_fitting_Callback(hObject, eventdata, handles)
function dropdown_fitting_CreateFcn(hObject, eventdata, handles)
function edit_fittingWindow_Callback(hObject, eventdata, handles)
function edit_fittingWindow_CreateFcn(hObject, eventdata, handles)
function edit_mWpower_Callback(hObject, eventdata, handles)
function edit_mWpower_CreateFcn(hObject, eventdata, handles)
function dropdown_view_Callback(hObject, eventdata, handles)
function dropdown_view_CreateFcn(hObject, eventdata, handles)
function [handles] = slider1_Callback(hObject, eventdata, handles)
function slider1_CreateFcn(hObject, eventdata, handles)
function checkbox_PSfits_Callback(hObject, eventdata, handles)
function checkbox_errorbars_Callback(hObject, eventdata, handles)
function CFOxyP_Callback(hObject, eventdata, handles)
function CFOxyP_CreateFcn(hObject, eventdata, handles)
function CFOxyPM_Callback(hObject, eventdata, handles)
function CFOxyPM_CreateFcn(hObject, eventdata, handles)
function CFOxyA_Callback(hObject, eventdata, handles)
function CFOxyA_CreateFcn(hObject, eventdata, handles)
function CFOxyB_Callback(hObject, eventdata, handles)
function CFOxyB_CreateFcn(hObject, eventdata, handles)
function CFN2P_Callback(hObject, eventdata, handles)
function CFN2P_CreateFcn(hObject, eventdata, handles)
function CFN2PM_Callback(hObject, eventdata, handles)
function CFN2PM_CreateFcn(hObject, eventdata, handles)
function CFN2A_Callback(hObject, eventdata, handles)
function CFN2A_CreateFcn(hObject, eventdata, handles)
function CFN2B_Callback(hObject, eventdata, handles)
function CFN2B_CreateFcn(hObject, eventdata, handles)
function CFNiP_Callback(hObject, eventdata, handles)
function CFNiP_CreateFcn(hObject, eventdata, handles)
function CFNiPM_Callback(hObject, eventdata, handles)
function CFNiPM_CreateFcn(hObject, eventdata, handles)
function CFNiA_Callback(hObject, eventdata, handles)
function CFNiA_CreateFcn(hObject, eventdata, handles)
function CFNiB_Callback(hObject, eventdata, handles)
function CFNiB_CreateFcn(hObject, eventdata, handles)
function edit_pi_Oxy_Callback(hObject, eventdata, handles)
function edit_pi_Oxy_CreateFcn(hObject, eventdata, handles)
function edit_pi_N2_Callback(hObject, eventdata, handles)
function edit_pi_N2_CreateFcn(hObject, eventdata, handles)
function edit_pi_Ni_Callback(hObject, eventdata, handles)
function edit_pi_Ni_CreateFcn(hObject, eventdata, handles)
function menu_file_Callback(hObject, eventdata, handles)
function menu_open_Callback(hObject, eventdata, handles)
function menu_save_Callback(hObject, eventdata, handles)
function menu_reset_Callback(hObject, eventdata, handles)
function menu_close_Callback(hObject, eventdata, handles)
function menu_DS_Callback(hObject, eventdata, handles)
function menu_DS_oxy_Callback(hObject, eventdata, handles)
function menu_DS_oxy1_Callback(hObject, eventdata, handles)
function menu_DS_oxy2_Callback(hObject, eventdata, handles)
function menu_DS_N2_Callback(hObject, eventdata, handles)
function menu_DS_N21_Callback(hObject, eventdata, handles)
function menu_DS_N22_Callback(hObject, eventdata, handles)
function menu_DS_Ni_Callback(hObject, eventdata, handles)
function menu_DS_Ni1_Callback(hObject, eventdata, handles)
function menu_DS_Ni2_Callback(hObject, eventdata, handles)
function menu_DS_DPPH_Callback(hObject, eventdata, handles)
function menu_DS_DPPH1_Callback(hObject, eventdata, handles)
function menu_DS_DPPH2_Callback(hObject, eventdata, handles)
function menu_spectra_Callback(hObject, eventdata, handles)
function menu_spec_clear_Callback(hObject, eventdata, handles)
function menu_spec_replot_Callback(hObject, eventdata, handles)
function menu_spec_detach_Callback(hObject, eventdata, handles)
function menu_spec_save_Callback(hObject, eventdata, handles)
function menu_PS_Callback(hObject, eventdata, handles)
function menu_PS_export_Callback(hObject, eventdata, handles)
function menu_PS_Origin_Callback(hObject, eventdata, handles)
function menu_PS_replot_Callback(hObject, eventdata, handles)
function menu_PS_detach_Callback(hObject, eventdata, handles)
function menu_PS_save_Callback(hObject, eventdata, handles)
function menu_PS_clear_Callback(hObject, eventdata, handles)
function menu_help_Callback(hObject, eventdata, handles)
function menu_help_help_Callback(hObject, eventdata, handles)
function help_about_Callback(hObject, eventdata, handles)
SOURCE CODE
function varargout = PowerSat(varargin)
% POWERSAT Open, analyse and plot power saturation experiments
%      POWERSAT, is designed as a complete solution for power saturation
%      experiments. Taking raw spectra straight from the spectrometer and
%      turning them into Power Saturation curves and accessibility
%      parameters (Pi values) in seconds.
%
%      POWERSAT, loads Bruker BES3T files either as a single file (actually
%      3 files with the extensions .DTA / .DSC / .YGF extensions) or an
%      entire folder of files (with the Bruker BES3T format (.DTA/.DSC) or
%      the older Bruker format still used on EMX machines (.spc/.par). If a
%      folder load method is used then each of the oxygen, nitrogen, NiEDDA
%      and DPPH experiments data files need to be in a different folders.
%
%      REFERENCES:
%      ===========
%
%      This calculations in this program are all derived from:
%       Accessibility of Nitroxide Side Chains: Absolute Heisenberg
%       Exchange Rates from Power Saturation EPR
%       Biophysical Journal, vol 89 (2005) 2103 - 2112.
%       DOI: 10.1529/biophysj.105.059063
%
%      Equations for first and second derivative Gaussian and Lorentzian
%       functions are taken from:
%       http://www.hulinks.co.jp/software/peakfit/functions.html
%
%      RELEASE NOTES:
%      ==============
%
%      Since POWERSAT v12.7 uses MATLAB's Curve Fitting toolbox for the
%      fitting of the Gaussian or Lorentzian profiles to raw data as well
%      as fitting power saturation curves. This is due to the CFtoolbox
%      giving greater control and flexibility to fitting.
%
%      POWERSAT v12.6 and before instead used the freely
%      available toolbox EzyFit.
%       www.fast.u-psud.fr/ezyfit/
%
%      This method was discontinued as the EzyFit toolbox allows for no
%      restriction of coefficient ranges during fitting. This often meant
%      that during the fitting of the power saturation curves that a
%      local minima for "a" was found below zero, giving an incorrect fit;
%      usually in the shape of a diagonal line with a loop in the middle.
%      This problem whilst promised to be fixed in an upcoming release of
%      Ezyfit (in personal correspondance with the author) has been
%      outstanding for over a year.
%
%      If users, do not wish to use the CFtoolbox then it is recommended to
%      install a version of POWERSAT prior to v12.7, still available at:
%      http://sourceforge.net/projects/eprtoolbox/files/PowerSat/PowerSat_v11.11.zip/download
%
%      Demonstration videos are available on YouTube:
%       Basic functionality - http://youtu.be/n8wWRzHoF-8
%       Fitting options     - http://youtu.be/DstC7ysrYG0
%
%
% Syntax:  PowerSat
%
% Inputs:
%    input1 - n/a
%
% Outputs:
%    output1 - n/a
%
% Example:
%    see http://morganbye.net/PowerSat
%        http://youtu.be/n8wWRzHoF-8
%        http://youtu.be/DstC7ysrYG0
%
% Other m-files required:
%    PowerSat.fig
%    Curve Fitting Toolbox - fit, fittype, coeffvalues
%    BrukerRead
%
% Subfunctions:         /_private (folder)
%
% MAT-files required:   none
%
%
%                                        _                             _
%                                       | |                           | |
%  _ __ ___   ___  _ __ __ _  __ _ _ __ | |__  _   _  ___   _ __   ___| |_
% | '_ ` _ \ / _ \| '__/ _` |/ _` | '_ \| '_ \| | | |/ _ \ | '_ \ / _ \ __|
% | | | | | | (_) | | | (_| | (_| | | | | |_) | |_| |  __/_| | | |  __/ |_
% |_| |_| |_|\___/|_|  \__, |\__,_|_| |_|_.__/ \__, |\___(_)_| |_|\___|\__|
%                       __/ |                   __/ |
%                      |___/                   |___/
%
%
% M. Bye v13.08
%
% Author:       Morgan Bye
% Work address: Henry Wellcome Unit for Biological EPR
%               University of East Anglia
%               NORWICH, UK
% Email:        morgan.bye@uea.ac.uk
% Website:      http://www.morganbye.net/PowerSat
% Aug 2013;     Last revision: 05-August-2013
%
% Version history:
% Aug 13        > Added web URL to title bar
%               > Help option opens web browser to PowerSat page
%
% Jul 13        Added an "Export to Origin" option in the PowerSat Curves
%                   menu. This will export the current power saturation
%                   curves into an Origin friendly file that includes the
%                   data points, error bars and fit lines.
%
%
% Mar 13        > When loading a file, check added to see if file has already
%               been loaded. If so, erases previous file, preventing errors
%               and allows for better file comparison.
%               > File > Reset all now clears the old data files and axes
%               instead of opening a new instance of PowerSat and closing
%               the old one
%               > Changed PS_Pi so that Pi is calculated faster and
%               calculated automatically if N2 and DPPH have been loaded,
%               it does not wait for all 4 datasets to be loaded.
%
% Dec 12        > Multiple fixes for folder loading, and then peak finding
%                   and processing as multiple files may not necessarily
%                   have the same x-axes
%               > Removed progressbar errors, replaced with waitbar
%               > Better figure saving and exporting
%               > Removed legacy code to EzyFit and error bar options from
%                   when error bars were plotted as SDs of the data
%
% Aug 12        > New Gaussian and Lorentzian derivative fitting methods
%
%               > Change from Gaussian tickbox to a fitting dropdown menu
%                   for Lorentzian fitting
%
% Jun 12        Another big overhaul of the PowerSat function
%               > New menu system
%               > Better loading and handling of files
%               > Bruker .DTA and .spc support
%               > Support for loading a folder of files, not just a 3D
%                   Bruker BE3ST file (.DTA/.DSC/.YGF)
%               > EzyFit toolbox has been replaced with the MATLAB Curve
%                   Fitting Toolbox for better fitting control
%               > Peak finding is now done via a Gaussian curve fit to the
%                   data (this can be toggled in the Dataset Manipulation
%                   panel - which replaces the digital smoothing function
%                   used previously)
%               > Ability to save and later load a session without having
%               to reload all the spectra files.
%               > Export the PowerSat curve data to the MATLAB workspace
%
% Oct 11        > Massive overhaul of function into a "modular" form.
%               Giving large speed increase, better maintaince and
%               documentation.
%               > Removed ~ (tilde) variables from program, although it
%               should work in all MATLAB (and does on Linux) it causes
%               problems for Windows users.
%               > GUI objects moved, for better visualisation on Windows
%
% Sept 11       > Removed need for external files by adding additional
%               functions to end of file (except BrukerRead)
%               > Loaded spectra are autozeroed when displayed in Datasets
%               window
%               > Datasets scrollbar only appears when individual plots are
%               displayed
%               > "Show all plots" tick boxes removed and replaced by a
%               view dropdown menu
%               > Plotting code stream lined and now with better error
%               catching
%               > Digital smoothing feature of loaded spectra, useful for
%               noisy spectra, but should be used carefully
%               > DPPH file load option, allows for "Pi" accessbility
%               factor to be calculated
%               > Error bars added to Power Saturation curve data points,
%               calculated by a standard deviation of the noise.
% Last Modified by GUIDE v2.5 17-Jul-2013 16:39:01
% Begin initialization code - DO NOT EDIT
gui_Singleton = 0;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @PowerSat_OpeningFcn, ...
                   'gui_OutputFcn',  @PowerSat_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT
% --- Executes just before PowerSat is made visible.
function PowerSat_OpeningFcn(hObject, eventdata, handles, varargin)
clear global vars
% Check fitting program exists
if exist('cftool') == 0,
        warndlg(sprintf('The Curve Fitting Toolbox could not be found on your system.\n\nWithout it this program will show very little functionality as the P1/2s cannot be calculated and no Gaussian fitting can be used\n\n'),'Curve Fitting Toolbox missing')
end
% Choose default command line statusbar for PowerSat
handles.statusbar = hObject;
% Name the window
set(gcf,'Name','PowerSat - v13.08 - morganbye.net/PowerSat');
% Update handles structure
% set(hObject,'toolbar','figure');
set(handles.panel_Plot,'SelectionChangeFcn',@panel_Plot_SelectionChangeFcn);
axes(handles.plot_load);
xlabel('Magnetic Field / Gauss');
ylabel('Intensity');
axes(handles.plot_PS);
xlabel('\surd Microwave Power / mW^½');
ylabel('Y'' / arb. units');
set(handles.slider1,'Value',1);
set(handles.slider1,'Min',1);
set(handles.slider1,'Visible','off');
set(handles.checkbox_autozero,'Value',1);
guidata(hObject, handles);
% UIWAIT makes PowerSat wait for user response (see UIRESUME)
% uiwait(handles.figure1);
% --- Outputs from this function are returned to the command line.
function varargout = PowerSat_OutputFcn(hObject, eventdata, handles)
varargout{1} = handles.statusbar;
%          ===================================================
%          ===================================================
%                     Dataset Manipulation Panel
%          ===================================================
%          ===================================================
% ===================================================
% Radio Buttons
% ===================================================
% --- Radio buttons in Plot Selection
function panel_Plot_SelectionChangeFcn(hObject, eventdata, handles)
handles = guidata(hObject);
set(handles.slider1,'Value',1);
PS_Plot1(handles)
guidata(hObject, handles);
% ===================================================
% User input (text fields)
% ===================================================
% Oxygen
% ===================================================
function edit_OxyHigh_Callback(hObject, eventdata, handles)
set(handles.button_OxySelect,'Value',1)     % Select Oxy
input = str2num(get(hObject,'String'));     % Convert input to number
if (isempty(input))                         % If empty then catch
     set(hObject,'String','-')
else
    global vars
    vars.Oxy.MaxPeak = input;
end
PS_Plot1(handles)                           % Replot with new values
PS_PlotPS(handles);
guidata(hObject, handles);
% --- Executes during object creation, after setting all properties.
function edit_OxyHigh_CreateFcn(hObject, eventdata, handles)
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_OxyLow_Callback(hObject, eventdata, handles)
set(handles.button_OxySelect,'Value',1)
input = str2num(get(hObject,'String'));
if (isempty(input))
     set(hObject,'String','-')
else
    global vars
    vars.Oxy.MinPeak = input;
end
PS_Plot1(handles)
PS_PlotPS(handles);
guidata(hObject, handles);
% --- Executes during object creation, after setting all properties.
function edit_OxyLow_CreateFcn(hObject, eventdata, handles)
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% Nitrogen
% ===================================================
function edit_N2High_Callback(hObject, eventdata, handles)
set(handles.button_N2Select,'Value',1)
input = str2num(get(hObject,'String'));
if (isempty(input))
     set(hObject,'String','-')
else
    global vars
    vars.N2.MaxPeak = input;
end
PS_Plot1(handles)
PS_PlotPS(handles);
guidata(hObject, handles);
% --- Executes during object creation, after setting all properties.
function edit_N2High_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_N2Low_Callback(hObject, eventdata, handles)
set(handles.button_N2Select,'Value',1)
input = str2num(get(hObject,'String'));
if (isempty(input))
     set(hObject,'String','-')
else
    global vars
    vars.N2.MinPeak = input;
end
PS_Plot1(handles)
PS_PlotPS(handles);
guidata(hObject, handles);
% --- Executes during object creation, after setting all properties.
function edit_N2Low_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% NiEDDA
% ===================================================
function edit_NiHigh_Callback(hObject, eventdata, handles)
set(handles.button_NiSelect,'Value',1)
input = str2num(get(hObject,'String'));
if (isempty(input))
     set(hObject,'String','-')
else
    global vars
    vars.Ni.MaxPeak = input;
end
PS_Plot1(handles)
PS_PlotPS(handles);
guidata(hObject, handles);
% --- Executes during object creation, after setting all properties.
function edit_NiHigh_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_NiLow_Callback(hObject, eventdata, handles)
set(handles.button_NiSelect,'Value',1)
input = str2num(get(hObject,'String'));
if (isempty(input))
     set(hObject,'String','-')
else
    global vars
    vars.Ni.MinPeak = input;
end
PS_Plot1(handles)
PS_PlotPS(handles);
guidata(hObject, handles);
% --- Executes during object creation, after setting all properties.
function edit_NiLow_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% DPPH
% ===================================================
function edit_DPPHHigh_Callback(hObject, eventdata, handles)
set(handles.button_DPPHSelect,'Value',1)
input = str2num(get(hObject,'String'));
if (isempty(input))
     set(hObject,'String','-')
else
    global vars
    vars.DPPH.MaxPeak = input;
end
PS_Plot1(handles)
PS_PlotPS(handles);
guidata(hObject, handles);
% --- Executes during object creation, after setting all properties.
function edit_DPPHHigh_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_DPPHLow_Callback(hObject, eventdata, handles)
set(handles.button_DPPHSelect,'Value',1)
input = str2num(get(hObject,'String'));
if (isempty(input))
     set(hObject,'String','-')
else
    global vars
    vars.DPPH.MinPeak = input;
end
PS_Plot1(handles)
PS_PlotPS(handles);
guidata(hObject, handles);
% --- Executes during object creation, after setting all properties.
function edit_DPPHLow_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
%          ===================================================
%          ===================================================
%                     Dataset Manipulation Panel
%          ===================================================
%          ===================================================
% --- Executes on button press in checkbox_autozero.
function checkbox_autozero_Callback(hObject, eventdata, handles)
PS_Plot1(handles);
PS_PlotPS(handles);
% --- Executes on selection change in dropdown_fitting.
function dropdown_fitting_Callback(hObject, eventdata, handles)
PS_Plot1(handles);
PS_PlotPS(handles);
% --- Executes during object creation, after setting all properties.
function dropdown_fitting_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_fittingWindow_Callback(hObject, eventdata, handles)
PS_Plot1(handles);
PS_PlotPS(handles);
% --- Executes during object creation, after setting all properties.
function edit_fittingWindow_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
%          ===================================================
%          ===================================================
%                        Viewing options panel
%          ===================================================
%          ===================================================
function edit_mWpower_Callback(hObject, eventdata, handles)
PS_Plot1(handles);
% --- Executes during object creation, after setting all properties.
function edit_mWpower_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on selection change in dropdown_view.
function dropdown_view_Callback(hObject, eventdata, handles)
PS_Plot1(handles);
% --- Executes during object creation, after setting all properties.
function dropdown_view_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
%          ===================================================
%          ===================================================
%                          Spectra Panel
%          ===================================================
%          ===================================================
% --- Executes on Slider movement.
function [handles] = slider1_Callback(hObject, eventdata, handles)
PS_Plot1(handles)
% --- Executes during object creation, after setting all properties.
function slider1_CreateFcn(hObject, eventdata, handles)
if isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor',[.9 .9 .9]);
end
%          ===================================================
%          ===================================================
%                        PS Curves Panel
%          ===================================================
%          ===================================================
% No options here.
%          ===================================================
%          ===================================================
%                        PS Options Panel
%          ===================================================
%          ===================================================
% --- Executes on button press in checkbox_PSfits.
function checkbox_PSfits_Callback(hObject, eventdata, handles)
PS_PlotPS(handles);
% --- Executes on button press in checkbox_errorbars.
function checkbox_errorbars_Callback(hObject, eventdata, handles)
PS_PlotPS(handles);
%          ===================================================
%          ===================================================
%                             PS Data Panel
%          ===================================================
%          ===================================================
% Oxygen
% ===================================================
function CFOxyP_Callback(hObject, eventdata, handles)
% --- Executes during object creation, after setting all properties.
function CFOxyP_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function CFOxyPM_Callback(hObject, eventdata, handles)
% --- Executes during object creation, after setting all properties.
function CFOxyPM_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function CFOxyA_Callback(hObject, eventdata, handles)
% --- Executes during object creation, after setting all properties.
function CFOxyA_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function CFOxyB_Callback(hObject, eventdata, handles)
% --- Executes during object creation, after setting all properties.
function CFOxyB_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% Nitrogen
% ===================================================
function CFN2P_Callback(hObject, eventdata, handles)
% --- Executes during object creation, after setting all properties.
function CFN2P_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function CFN2PM_Callback(hObject, eventdata, handles)
% --- Executes during object creation, after setting all properties.
function CFN2PM_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function CFN2A_Callback(hObject, eventdata, handles)
% --- Executes during object creation, after setting all properties.
function CFN2A_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function CFN2B_Callback(hObject, eventdata, handles)
% --- Executes during object creation, after setting all properties.
function CFN2B_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% NiEDDA
% ===================================================
function CFNiP_Callback(hObject, eventdata, handles)
% --- Executes during object creation, after setting all properties.
function CFNiP_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function CFNiPM_Callback(hObject, eventdata, handles)
% --- Executes during object creation, after setting all properties.
function CFNiPM_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function CFNiA_Callback(hObject, eventdata, handles)
% --- Executes during object creation, after setting all properties.
function CFNiA_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function CFNiB_Callback(hObject, eventdata, handles)
% --- Executes during object creation, after setting all properties.
function CFNiB_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
%          ===================================================
%          ===================================================
%                     Accessibility Panel
%          ===================================================
%          ===================================================
function edit_pi_Oxy_Callback(hObject, eventdata, handles)
function edit_pi_Oxy_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_pi_N2_Callback(hObject, eventdata, handles)
% --- Executes during object creation, after setting all properties.
function edit_pi_N2_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_pi_Ni_Callback(hObject, eventdata, handles)
% --- Executes during object creation, after setting all properties.
function edit_pi_Ni_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
%          ===================================================
%          ===================================================
%                                Menu
%          ===================================================
%          ===================================================
% File
% ===================================================
% --------------------------------------------------------------------
function menu_file_Callback(hObject, eventdata, handles)
% --------------------------------------------------------------------
function menu_open_Callback(hObject, eventdata, handles)
global vars
% GUI get file
[file , directory] = uigetfile({'*.mat','MATLAB structure (*.mat)'},'Load PowerSat file');
address = [directory,file];
% Load variable
load(address , 'vars');
% Update plots
PS_Plot1(handles);
if isfield(vars,'DPPH')
    set(handles.button_DPPHSelect ,'Value',1)
    set(handles.edit_DPPHHigh,'String',vars.DPPH.MaxPeak);
    set(handles.edit_DPPHLow ,'String',vars.DPPH.MinPeak);
elseif isfield(vars,'Ni')
    set(handles.button_NiSelect ,'Value',1)
    set(handles.edit_NiHigh,'String',vars.Ni.MaxPeak);
    set(handles.edit_NiLow ,'String',vars.Ni.MinPeak);
elseif isfield(vars,'N2')
    set(handles.button_N2Select ,'Value',1)
    set(handles.edit_N2High,'String',vars.N2.MaxPeak);
    set(handles.edit_N2Low ,'String',vars.N2.MinPeak);
elseif isfield(vars,'Oxy')
    set(handles.button_OxySelect ,'Value',1)
    set(handles.edit_OxyHigh,'String',vars.Oxy.MaxPeak);
    set(handles.edit_OxyLow ,'String',vars.Oxy.MinPeak);
else
    return
end
PS_PlotPS(handles);
% --------------------------------------------------------------------
function menu_save_Callback(hObject, eventdata, handles)
global vars
[file, pathname] = uiputfile({ '*.mat','MATLAB structure (*.mat)'},...
        'Save PowerSat as','default');
address = [pathname file];
save(address,'vars');
% --------------------------------------------------------------------
function menu_reset_Callback(hObject, eventdata, handles)
% OLD METHOD: basically calls a new figure on top of old
% closeGUI = handles.figure1;                     % handles.figure1 is the GUI figure
%
% guiPosition = get(handles.figure1,'Position');  % get the position of the GUI
% guiName = get(handles.figure1,'Name');          % get the name of the GUI
% eval('PowerSat')                                % call the GUI again
%
% close(closeGUI);                                % close the old GUI
% set(gcf,'Position',guiPosition);                % set the position for the new GUI
%
% clear global
% NEW METHOD: clear variables, reset axes
close = questdlg(...
    'Are you sure you want to reset PowerSat? This will clear all unsaved data.',...
    'Reset PowerSat?',...
    'Yes',...
    'No',...
    'Yes');
switch strcmp(close,'Yes')
    case 1
        global vars
        vars.Oxy = [];
        vars.N2 = [];
        vars.Ni = [];
        vars.DPPH = [];
        cla(handles.plot_load);
        xlabel('Magnetic Field / Gauss');
        ylabel('Intensity');
        cla(handles.plot_PS);
        xlabel('\surd Microwave Power / mW^½');
        ylabel('Y'' / arb. units');
        set(handles.edit_OxyHigh,'String','-');
        set(handles.edit_OxyLow,'String','-');
        set(handles.edit_N2High,'String','-');
        set(handles.edit_N2Low,'String','-');
        set(handles.edit_NiHigh,'String','-');
        set(handles.edit_NiLow,'String','-');
        set(handles.edit_DPPHHigh,'String','-');
        set(handles.edit_DPPHLow,'String','-');
        set(handles.button_OxySelect ,'Value',1);
        set(handles.checkbox_autozero,'Value',1);
        set(handles.dropdown_view    ,'Value',1);
        set(handles.CFOxyP,'String','-');
        set(handles.CFOxyA,'String','-');
        set(handles.CFOxyB,'String','-');
        set(handles.CFOxyR,'String','-');
        set(handles.CFN2P,'String','-');
        set(handles.CFN2A,'String','-');
        set(handles.CFN2B,'String','-');
        set(handles.CFN2R,'String','-');
        set(handles.CFNiP,'String','-');
        set(handles.CFNiA,'String','-');
        set(handles.CFNiB,'String','-');
        set(handles.CFNiR,'String','-');
        set(handles.edit_pi_Oxy,'String','-');
        set(handles.edit_pi_Ni,'String','-');
    case 0
end
% --------------------------------------------------------------------
function menu_close_Callback(hObject, eventdata, handles)
figure1_CloseRequestFcn
% Datasets
% ===================================================
% --------------------------------------------------------------------
function menu_DS_Callback(hObject, eventdata, handles)
% --------------------------------------------------------------------
function menu_DS_oxy_Callback(hObject, eventdata, handles)
% --------------------------------------------------------------------
function menu_DS_oxy1_Callback(hObject, eventdata, handles)
global vars
% This creates a structure or overwrites an old one
vars.Oxy = [];
% Set defaults
set(handles.button_OxySelect ,'Value',1);
set(handles.checkbox_autozero,'Value',1);
set(handles.dropdown_view    ,'Value',1);
% Load and plot file
PS_FileLoad('Oxy','file');
PS_Plot1(handles);
% Update data boxes in GUI
set(handles.edit_mWpower,'String','All');
set(handles.edit_OxyHigh,'String',vars.Oxy.MaxPeak);
set(handles.edit_OxyLow ,'String',vars.Oxy.MinPeak);
PS_PlotPS(handles);
guidata(hObject, handles);
1000 % --------------------------------------------------------------------
1001 function menu_DS_oxy2_Callback(hObject, eventdata, handles)
1002
1003 global vars
1004 % This creates a structure or overwrites an old one
1005 vars.Oxy = [];
1006
1007 % Set defaults
1008 set(handles.button_OxySelect ,'Value',1)
1009 set(handles.checkbox_autozero,'Value',1);
1010 set(handles.dropdown_view    ,'Value',1);
1011
1012 % Load and plot file
1013 PS_FileLoad('Oxy','folder');
1014 PS_Plot1(handles);
1015
1016 % Update data boxes in GUI
1017 set(handles.edit_mWpower,'String','All');
1018 set(handles.edit_OxyHigh,'String',vars.Oxy.MaxPeak);
1019 set(handles.edit_OxyLow ,'String',vars.Oxy.MinPeak);
1020
1021 PS_PlotPS(handles);
1022
1023 guidata(hObject, handles);
1024
1025
1026 % --------------------------------------------------------------------
1027 function menu_DS_N2_Callback(hObject, eventdata, handles)
1028
1029
1030 % --------------------------------------------------------------------
1031 function menu_DS_N21_Callback(hObject, eventdata, handles)
1032
1033 global vars
1034 % This creates a structure or overwrites an old one
1035 vars.N2 = [];
1036
1037 % Set defaults
1038 set(handles.button_N2Select  ,'Value',1)
1039 set(handles.checkbox_autozero,'Value',1);
1040 set(handles.dropdown_view    ,'Value',1);
1041
1042 % Load and plot file
1043 PS_FileLoad('N2','file');
1044 PS_Plot1(handles);
1045
1046 % Update data boxes in GUI
1047 set(handles.edit_mWpower,'String','All');
1048 set(handles.edit_N2High,'String',vars.N2.MaxPeak);
1049 set(handles.edit_N2Low ,'String',vars.N2.MinPeak);
1050
1051 PS_PlotPS(handles);
1052
1053 guidata(hObject, handles);
1054
1055 % --------------------------------------------------------------------
1056 function menu_DS_N22_Callback(hObject, eventdata, handles)
1057
1058 global vars
1059 % This creates a structure or overwrites an old one
1060 vars.N2 = [];
1061
1062 % Set defaults
1063 set(handles.button_N2Select  ,'Value',1)
1064 set(handles.checkbox_autozero,'Value',1);
1065 set(handles.dropdown_view    ,'Value',1);
1066
1067 % Load and plot file
1068 PS_FileLoad('N2','folder');
1069 PS_Plot1(handles);
1070
1071 % Update data boxes in GUI
1072 set(handles.edit_mWpower,'String','All');
1073 set(handles.edit_N2High,'String',vars.N2.MaxPeak);
1074 set(handles.edit_N2Low ,'String',vars.N2.MinPeak);
1075
1076 PS_PlotPS(handles);
1077
1078 guidata(hObject, handles);
1079
1080 % --------------------------------------------------------------------
1081 function menu_DS_Ni_Callback(hObject, eventdata, handles)
1082
1083 % --------------------------------------------------------------------
1084 function menu_DS_Ni1_Callback(hObject, eventdata, handles)
1085
1086 global vars
1087 % This creates a structure or overwrites an old one
1088 vars.Ni = [];
1089
1090 % Set defaults
1091 set(handles.button_NiSelect ,'Value',1)
1092 set(handles.checkbox_autozero,'Value',1);
1093 set(handles.dropdown_view    ,'Value',1);
1094
1095 % Load and plot file
1096 PS_FileLoad('Ni','file');
1097 PS_Plot1(handles);
1098
1099 % Update data boxes in GUI
1100 set(handles.edit_mWpower,'String','All');
1101 set(handles.edit_NiHigh,'String',vars.Ni.MaxPeak);
1102 set(handles.edit_NiLow ,'String',vars.Ni.MinPeak);
1103
1104 PS_PlotPS(handles);
1105
1106 guidata(hObject, handles);
1107
1108 % --------------------------------------------------------------------
1109 function menu_DS_Ni2_Callback(hObject, eventdata, handles)
1110
1111 global vars
1112 % This creates a structure or overwrites an old one
1113 vars.Ni = [];
1114
1115 % Set defaults
1116 set(handles.button_NiSelect ,'Value',1)
1117 set(handles.checkbox_autozero,'Value',1);
1118 set(handles.dropdown_view    ,'Value',1);
1119
1120 % Load and plot file
1121 PS_FileLoad('Ni','folder');
1122 PS_Plot1(handles);
1123
1124 % Update data boxes in GUI
1125 set(handles.edit_mWpower,'String','All');
1126 set(handles.edit_NiHigh,'String',vars.Ni.MaxPeak);
1127 set(handles.edit_NiLow ,'String',vars.Ni.MinPeak);
1128
1129 PS_PlotPS(handles);
1130
1131 guidata(hObject, handles);
1132
1133 % --------------------------------------------------------------------
1134 function menu_DS_DPPH_Callback(hObject, eventdata, handles)
1135
1136 % --------------------------------------------------------------------
1137 function menu_DS_DPPH1_Callback(hObject, eventdata, handles)
1138
1139 global vars
1140 % This creates a structure or overwrites an old one
1141 vars.DPPH = [];
1142
1143 % Set defaults
1144 set(handles.button_DPPHSelect,'Value',1)
1145 set(handles.checkbox_autozero,'Value',1);
1146 set(handles.dropdown_view    ,'Value',1);
1147
1148 % Load and plot file
1149 PS_FileLoad('DPPH','file');
1150 PS_Plot1(handles);
1151
1152 % Update data boxes in GUI
1153 set(handles.edit_mWpower,'String','All');
1154 set(handles.edit_DPPHHigh,'String',vars.DPPH.MaxPeak);
1155 set(handles.edit_DPPHLow ,'String',vars.DPPH.MinPeak);
1156
1157 PS_PlotPS(handles);
1158
1159 guidata(hObject, handles);
1160
1161
1162 % --------------------------------------------------------------------
1163 function menu_DS_DPPH2_Callback(hObject, eventdata, handles)
1164
1165 global vars
1166 % This creates a structure or overwrites an old one
1167 vars.DPPH = [];
1168
1169 % Set defaults
1170 set(handles.button_DPPHSelect,'Value',1)
1171 set(handles.checkbox_autozero,'Value',1);
1172 set(handles.dropdown_view    ,'Value',1);
1173
1174 % Load and plot file
1175 PS_FileLoad('DPPH','folder');
1176 PS_Plot1(handles);
1177
1178 % Update data boxes in GUI
1179 set(handles.edit_mWpower,'String','All');
1180 set(handles.edit_DPPHHigh,'String',vars.DPPH.MaxPeak);
1181 set(handles.edit_DPPHLow ,'String',vars.DPPH.MinPeak);
1182
1183 PS_PlotPS(handles);
1184
1185 guidata(hObject, handles);
1186
1187
1188 % Spectra
1189 % ===================================================
1190
1191 % --------------------------------------------------------------------
1192 function menu_spectra_Callback(hObject, eventdata, handles)
1193
1194
1195 % --------------------------------------------------------------------
1196 function menu_spec_clear_Callback(hObject, eventdata, handles)
1197
1198 cla(handles.plot_load,'reset');
1199 guidata(hObject, handles);
1200
1201
1202 % --------------------------------------------------------------------
1203 function menu_spec_replot_Callback(hObject, eventdata, handles)
1204
1205 global vars
1206
1207 % if get(handles.checkbox_Gauss,'Value')
1208 %     if isfield(vars,'DPPH')
1209 %         PS_Plot1_Gaussian(handles,'DPPH')
1210 %     end
1211 %     if isfield(vars,'Ni')
1212 %         PS_Plot1_Gaussian(handles,'Ni')
1213 %     end
1214 %     if isfield(vars,'N2')
1215 %         PS_Plot1_Gaussian(handles,'N2')
1216 %     end
1217 %     if isfield(vars,'Oxy')
1218 %         PS_Plot1_Gaussian(handles,'Oxy')
1219 %     end
1220 % end
1221
1222 PS_Plot1(handles);
1223 PS_PlotPS(handles);
1224
1225
1226 % --------------------------------------------------------------------
1227 function menu_spec_detach_Callback(hObject, eventdata, handles)
1228
1229 PS_DetachPlot(handles.plot_load);
1230
1231
1232 % --------------------------------------------------------------------
1233 function menu_spec_save_Callback(hObject, eventdata, handles)
1234
1235 PS_SavePlot(handles.plot_load);
1236
1237
1238
1239 % PowerSat
1240 % ===================================================
1241
1242 % --------------------------------------------------------------------
1243 function menu_PS_Callback(hObject, eventdata, handles)
1244
1245 % --------------------------------------------------------------------
1246 function menu_PS_export_Callback(hObject, eventdata, handles)
1247
1248 global vars
1249
1250 if isfield(vars,'DPPH')
1251     out.Y           = vars.DPPH.Y;
1252     out.sqrtPower   = vars.DPPH.sqrtPower;
1253     out.FitResults  = vars.DPPH.FitResults;
1254
1255     assignin('base','DPPH',out)
1256 end
1257 if isfield(vars,'Ni')
1258     out.Y           = vars.Ni.Y;
1259     out.sqrtPower   = vars.Ni.sqrtPower;
1260     out.FitResults  = vars.Ni.FitResults;
1261
1262     assignin('base','Ni',out)
1263 end
1264 if isfield(vars,'N2')
1265     out.Y           = vars.N2.Y;
1266     out.sqrtPower   = vars.N2.sqrtPower;
1267     out.FitResults  = vars.N2.FitResults;
1268
1269     assignin('base','N2',out)
1270 end
1271 if isfield(vars,'Oxy')
1272     out.Y           = vars.Oxy.Y;
1273     out.sqrtPower   = vars.Oxy.sqrtPower;
1274     out.FitResults  = vars.Oxy.FitResults;
1275
1276     assignin('base','Oxy',out)
1277 end
1278
1279
1280 % --------------------------------------------------------------------
1281 function menu_PS_Origin_Callback(hObject, eventdata, handles)
1282
1283 PS_ExportToOrigin(handles);
1284
1285
1286 % --------------------------------------------------------------------
1287 function menu_PS_replot_Callback(hObject, eventdata, handles)
1288
1289 PS_PlotPS(handles);
1290
1291
1292 % --------------------------------------------------------------------
1293 function menu_PS_detach_Callback(hObject, eventdata, handles)
1294
1295 PS_DetachPlot(handles.plot_PS);
1296
1297 % --------------------------------------------------------------------
1298 function menu_PS_save_Callback(hObject, eventdata, handles)
1299
1300 PS_SavePlot(handles.plot_PS);
1301
1302
1303 % --------------------------------------------------------------------
1304 function menu_PS_clear_Callback(hObject, eventdata, handles)
1305
1306 cla(handles.plot_PS,'reset');
1307 guidata(hObject, handles);
1308
1309 % Help
1310 % ===================================================
1311
1312 % --------------------------------------------------------------------
1313 function menu_help_Callback(hObject, eventdata, handles)
1314
1315
1316 % --------------------------------------------------------------------
1317 function menu_help_help_Callback(hObject, eventdata, handles)
1318
1319 PS_Help_Help;
1320
1321
1322 % --------------------------------------------------------------------
1323 function help_about_Callback(hObject, eventdata, handles)
1324
1325 PS_Help_About;
1326